### ISSUE TITLE
mdbook 0.4.15 build fail with rustc 1.64, but works on rustc 1.62

### ISSUE THREAD

**Issue by dieterplex** [dieterplex/mdbook-epub#3]
According to https://github.com/rust-lang/rust/issues/99591
Unless we upgrade dependencies or use previous rustc, it would not compile:
```
> cargo test
   Compiling mdbook v0.4.15
error[E0597]: `local_ctx` does not live long enough
   --> /home/dieter/.cargo/registry/src/github.com-1ecc6299db9ec823/mdbook-0.4.15/src/renderer/html_handlebars/helpers/navigation.rs:154:25
    |
154 |             t.render(r, &local_ctx, &mut local_rc, out)
    |                         ^^^^^^^^^^ borrowed value does not live long enough
155 |         })?;
    |         -
    |         |
    |         `local_ctx` dropped here while still borrowed
    |         borrow might be used here, when `local_rc` is dropped and runs the destructor for type `handlebars::RenderContext<'_, '_>`
    |
    = note: values in a scope are dropped in the opposite order they are defined

For more information about this error, try `rustc --explain E0597`.
error: could not compile `mdbook` due to previous error
warning: build failed, waiting for other jobs to finish...
> rustc -V
rustc 1.64.0 (a55dd71d5 2022-09-19)
```

For 0.4.15 a workaround may still use 1.62 instead 

```
rustup toolchain intall 1.62
rustup default 1.62
```

**Comment by dieterplex** [comment]
Fix by upgrading mdbook version: https://github.com/dieterplex/mdbook-epub/commit/2ead376224ce7df76376a2d8de1b93f0d4714917.
